
### Cria um novo cartão

POST http://localhost:8081/cartoes
Content-Type: application/json

{
    "titular": "Sincrano Alves", "numero": "5183 3373 8522 6547", "vencimento": "11/21",
    "cpf": "214.720.460-99", "cvv": "853"
}

### Retorna a lista de cartões (R)

GET http://localhost:8081/cartoes

### Retorna o cartão de id = 1 (R)

GET http://localhost:8081/cartoes/1

### Atualiza o cartão (número, vencimento, cvv) de id = 3 (U)

PUT http://localhost:8081/cartoes/3 
Content-Type: application/json

{
    "titular": "Sincrano Alves", "numero": "4916 1338 6252 1766", "vencimento": "04/21",
    "cpf": "214.720.460-99", "cvv": "209"
}

### Remove o cartão de id = 3 (D)

DELETE http://localhost:8081/cartoes/3

### Cria uma nova transação

POST http://localhost:8081/transacoes
Content-Type: application/json

{
    "descricao": "Compra Online", "valor": 98.76, "data": "08/12/2019", 
    "categoria": "COMPRA", "status": "CONFIRMADA",
    "cartao": { "id": 1, "titular": "Beltrano Andrade", "numero": "5259 5697 2426 9163",
                "vencimento": "02/22", "cpf": "985.849.614-10", "cvv": "147"
              }
}

### Retorna a lista de transações (R)

GET http://localhost:8081/transacoes

### Retorna a transação de id = 1 (R)

GET http://localhost:8081/transacoes/1

### Atualiza a transação (apenas descrição) de id = 3 (U)

PUT http://localhost:8081/transacoes/3 
Content-Type: application/json 

{
    "descricao": "Compra Online Atualizada", "valor": 98.76, "data": "08/12/2019", 
    "categoria": "COMPRA", "status": "CONFIRMADA",
    "cartao": { "id": 1, "titular": "Beltrano Andrade", "numero": "5259 5697 2426 9163",
                 "vencimento": "02/22", "cpf": "985.849.614-10", "cvv": "147"
              }
}

### Atualiza a transação (descrição e cartão) de id = 3 (U)

PUT http://localhost:8081/transacoes/3 
Content-Type: application/json 

{
    "descricao": "Compra Online Atualizada Novamente", "valor": 98.76, "data": "08/12/2019", 
    "categoria": "COMPRA", "status": "CONFIRMADA",
    "cartao": { "id": 2, "titular": "Fulano Silva", "numero": "4929 5828 5594 8623",
                "vencimento": "12/21", "cpf": "367.318.380-04", "cvv": "663"
              }
}

### Remove a transação de id = 3 (D)

DELETE http://localhost:8081/transacoes/3